### ISSUE TITLE
Please update the vaadin-usage-statistics dependency

### ISSUE THREAD

**Issue by paulroemer** [vaadin/vaadin-element-mixin#3]
At the moment you are using v1.0.1 that does not support the new Flow namespace and Lumo. 1.0.5 is the latest release.

**Comment by jouni** [comment]
The dependency is set to `^1.0.1` in this package’s bower.json (for [v1.0.1](https://github.com/vaadin/vaadin-element-mixin/blob/v1.0.1/bower.json#L26) and [master](https://github.com/vaadin/vaadin-element-mixin/blob/master/bower.json#L26)), so it should pick up 1.0.5 just fine (the “hat” character `^` does that).

The problem must be somewhere else.
