### ISSUE TITLE
document.body === null

### ISSUE THREAD

**Issue by VForsmann** [vaadin/vaadin-element-mixin#37]
Hey!

Maybe I'm all wrong, saw you refactored the check of

`if (!window.document.body) {	        
          return 'indeterminate';	
 }`

in your new Version (vaadin-dir-helper).
I walk into a "Uncaught TypeError: Cannot read property 'appendChild' of null" because of that.
Did you do that especially so that you can use the vaadin components consciously after body initialization?

Thanks!

**Comment by web-padawan** [comment]
Hello, the original check was a copy-paste. My assumption is that `DirHelper` methods are called by the components instances, and by that point of time document body is defined.

Can you please share a code example? Does it fail when you import script in `<head>`?

**Comment by VForsmann** [comment]
Hey!
Ich checked with a clean install, seems i am doing something wrong with my setup, with the clean one everything is working.
Excuse my error message!
